repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        # so that it could use the config (like pyproject.toml) in out project
        language: system
        exclude: tests/

  - repo: local
    hooks:
      - id: migrations-check
        # in local dev env,
        # acitvate the python venv in cli
        # open the git commit IDE,  like VS Code`code .` or SourceTree
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "python manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [commit]

# enable pre-commit.ci
# refer to https://pre-commit.ci/
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
