repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: migrations-check
        # in local dev env,
        # acitvate the python venv in cli
        # open the git commit IDE,  like VS Code`code .` or SourceTree
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "python manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [commit]
