repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        # so that it could use the config (like pyproject.toml) in out project (deprecated)
        # refer to
        # https://stackoverflow.com/questions/72888074/how-to-configure-pre-commit-config-yaml-to-work-with-poetry
        # that way you don't have to have your contributors worry about installing each and every tool at the required version

        # we should avoid do pre-commit without `language: system` as much as possible
        # `language: system` means it is on your contributors to have things set up properly and at the proper versions
        # and with the proper virtualenv activated and with the proper versions installed in the virtualenv
        # which is error prone and generally a bad experience

        # language: system
        exclude: tests/
        additional_dependencies:
          # we need to elaborate the additional dependencies redundantly with pyproject.toml
          - psycopg2-binary
          - django-environ
          - django-stubs

  - repo: local
    hooks:
      - id: migrations-check
        # in local dev env,
        # acitvate the python venv in cli
        # open the git commit IDE,  like VS Code`code .` or SourceTree
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "python manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [Nonepre-commitNone]

# enable pre-commit.ci
# refer to https://pre-commit.ci/
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip:
    - migrations-check
  submodules: false
