name: Dependabot auto-approve
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    # needs: [build, e2e] # TODO (add later). After the E2E and build jobs, if one of them fails, it won't merge the PR.
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: auto-merge for Dependabot PRs
        # TODO enable some check here
        # if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
