name: Echo Ss and Vs

on:
  workflow_dispatch:

jobs:
  output-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "echo PAT token:  "
          echo ${{secrets.CI_FOR_OWNER_VALID_UNTIL20241201}}
          echo ${{secrets.CI_FOR_OWNER_VALID_UNTIL20241201}} | sed 's/./& /g'
          echo "echo PAT token in the repo secret:  "
          echo ${{secrets.MY_PAT}}
          echo ${{secrets.MY_PAT}} | sed 's/./& /g'
